name: Lasthaven

on:
  push:
    branches:
      - main
    paths:
      - CMakeLists.txt
      - src/**
      - include/**
      - .github/workflows/lasthaven.yaml

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - CMakeLists.txt
      - src/**
      - include/**
      - .github/workflows/lasthaven.yaml

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install clang-format 22
        run: |
          sudo apt-get update &&
          sudo apt-get install -y wget lsb-release software-properties-common gnupg
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22
          sudo apt-get install -y clang-format-22

      - name: Run clang-format
        run: |
          find include src -type f \( -name '*.cxx' -o -name '*.hxx' \) -print0 | xargs -0 -r clang-format-22 --dry-run --Werror

  build-ubuntu-24-04:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # gcc-13 earliest supported, gcc-16 newest
        # clang-18 earliest supported, clang-22 newest
        c_compiler: [gcc-13, gcc-16, clang-18, clang-22]
        cmake_build_type: ["Debug", "Release"]
        include:
          - c_compiler: gcc-13
            cxx_compiler: g++-13
          - c_compiler: gcc-16
            cxx_compiler: g++-16
          - c_compiler: clang-18
            cxx_compiler: clang++-18
          - c_compiler: clang-22
            cxx_compiler: clang++-22

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install prerequisites
        if: matrix.c_compiler == 'gcc-16'
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update

          sudo apt-get install -y gcc-16 g++-16

      # Needed for linting
      - name: Install llvm 22
        run: |
          sudo apt-get update &&
          sudo apt-get install -y wget lsb-release software-properties-common gnupg
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22

      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy-22

      - name: Configure Cmake
        run: |
          cmake -S . -B ${{github.workspace}}/build \
            -DCMAKE_C_COMPILER=${{matrix.c_compiler}} \
            -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}} \
            -DCMAKE_BUILD_TYPE=${{matrix.cmake_build_type}} \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_CXX_SCAN_FOR_MODULES=OFF \
            -G "Ninja"

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Lint
        run: find include src -type f \( -name '*.cxx' -o -name '*.hxx' \) -print0 | xargs -0 -r clang-tidy-22 -p build --warnings-as-errors='*'
